databases:
  - name: domain-monitor-db
    databaseName: domain_monitor
    user: domain_monitor
    plan: free

services:
    type: web
    name: domain-monitor
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: domain-monitor-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: ROLLBAR_ACCESS_TOKEN
        sync: false
      - key: SOLID_QUEUE_IN_PUMA
        value: "true"
      - key: WEB_CONCURRENCY
        value: "0"
      - key: RAILS_MAX_THREADS
        value: "5"
